# Site settings
title: Vanbein's Blog
email: vanbein520@gmail.com
author: Vanbein

description: This blog theme was designed by Frank Lin. I am updating this blog theme that meet my needs. Thanks to Github and Jekyll for the technical supports.

# Base url
url: "http://vanbein.com"

# Pre-processing  #Pygments

markdown: kramdown
highlighter: rouge
kramdown:
  input:          GFM
  auto_ids:       true
  syntax_highlighter: rouge
auto_id_prefix:  'id-'
safe: false
permalink: /posts/:categories/:title/

#YYYY/MM/DD/page-title/index.html # pretty

lsi: false # Lexical analysis (true) takes longer for higher quality

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
include:      [".htaccess"]
exclude:      ["vendor", "node_modules", "gulpfile.js", "package.json"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Lists
# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
tag_items: 20     # Applies to categories and tags lists
related_items: 3  # Fix 3 items in single post
recent_items: 20  # Applies to recent posts, apps lists
recent_posts: 6
paginate: 5       # Applies to blog page for pagination
# Pagination path › Important for blog page in /blog/ to work
paginate_path: "/blog/page:num/"
timezone:      null

# Plugins
whitelist: []
gems:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Embeds
google_api_key: "AIzaSyCJM2ZoBzZi3kQ0xf0u-r6Zs-j9huq8wfY"  #"AIzaSyDyjuRINP4K_rYn_JlSKVGxl-li36EIDBo" # https://code.google.com/apis/console/
# google api used for google maps

webmasters: ture
